/*==============================================================================
Application : GestionEleves
Version     : 1.4.0
Mode        : new_install
OldVersion	: all_or_none
==============================================================================*/

-- =============================================================================
--#TITLE(Désactivation des contraintes)

--#STEP(ALWAYS_RUN)
SET FOREIGN_KEY_CHECKS = 0;

--#STEP(ALWAYS_RUN)
SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

-- =============================================================================
--#TITLE(Création des tables)

-- Structure de la table CLASSES
--#STEP()
DROP TABLE IF EXISTS CLASSES;
CREATE TABLE `CLASSES` (
  `CLASSE_ID` int(11) NOT NULL auto_increment,
  `CLASSE_NOM` varchar(10) NOT NULL,
  `CLASSE_ANNEE_SCOLAIRE` varchar(9) NOT NULL,
  `ID_ECOLE` int(11) NOT NULL,
  PRIMARY KEY  (`CLASSE_ID`),
  KEY `ID_ECOLE` (`ID_ECOLE`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- Structure de la table COMPETENCES
--#STEP()
DROP TABLE IF EXISTS COMPETENCES;
CREATE TABLE `COMPETENCES` (
  `COMPETENCE_ID` int(11) NOT NULL auto_increment,
  `COMPETENCE_NOM` varchar(200) NOT NULL,
  `ID_MATIERE` int(11) NOT NULL,
  PRIMARY KEY  (`COMPETENCE_ID`),
  KEY `ID_MATIERE` (`ID_MATIERE`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- Structure de la table CYCLES
--#STEP()
DROP TABLE IF EXISTS CYCLES;
CREATE TABLE `CYCLES` (
  `CYCLE_ID` int(11) NOT NULL auto_increment,
  `CYCLE_NOM` varchar(50) NOT NULL,
  PRIMARY KEY  (`CYCLE_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- Structure de la table DOMAINES
--#STEP()
DROP TABLE IF EXISTS DOMAINES;
CREATE TABLE `DOMAINES` (
  `DOMAINE_ID` int(11) NOT NULL auto_increment,
  `DOMAINE_NOM` varchar(200) NOT NULL,
  `ID_CYCLE` int(11) NOT NULL,
  PRIMARY KEY  (`DOMAINE_ID`),
  KEY `ID_CYCLE` (`ID_CYCLE`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- Structure de la table ECOLES
--#STEP()
DROP TABLE IF EXISTS ECOLES;
CREATE TABLE `ECOLES` (
  `ECOLE_ID` int(11) NOT NULL auto_increment,
  `ECOLE_NOM` varchar(50) NOT NULL,
  `ECOLE_VILLE` varchar(50) NOT NULL,
  `ECOLE_DEPARTEMENT` varchar(5) NOT NULL,
  PRIMARY KEY  (`ECOLE_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- Structure de la table ELEVES
--#STEP()
DROP TABLE IF EXISTS ELEVES;
CREATE TABLE `ELEVES` (
  `ELEVE_ID` int(11) NOT NULL auto_increment,
  `ELEVE_NOM` varchar(50) NOT NULL,
  `ELEVE_ACTIF` tinyint(1) default '1',
  `ELEVE_DATE_NAISSANCE` date default NULL,
  PRIMARY KEY  (`ELEVE_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- Structure de la table ELEVE_CLASSE
--#STEP()
DROP TABLE IF EXISTS ELEVE_CLASSE;
CREATE TABLE `ELEVE_CLASSE` (
  `ID_ELEVE` int(11) NOT NULL,
  `ID_CLASSE` int(11) NOT NULL,
  PRIMARY KEY  (`ID_ELEVE`,`ID_CLASSE`),
  KEY `ID_CLASSE` (`ID_CLASSE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

-- Structure de la table EVALUATIONS_COLLECTIVES
--#STEP()
DROP TABLE IF EXISTS EVALUATIONS_COLLECTIVES;
CREATE TABLE `EVALUATIONS_COLLECTIVES` (
  `EVAL_COL_ID` int(11) NOT NULL auto_increment,
  `EVAL_COL_NOM` varchar(50) NOT NULL,
  `EVAL_COL_DESCRIPTION` varchar(200) NOT NULL,
  `EVAL_COL_DATE` date NOT NULL,
  `ID_PERIODE` int(11) NOT NULL,
  `ID_CLASSE` int(11) NOT NULL,
  PRIMARY KEY  (`EVAL_COL_ID`),
  KEY `ID_PERIODE` (`ID_PERIODE`),
  KEY `ID_CLASSE` (`ID_CLASSE`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

--
-- Structure de la table EVALUATIONS_INDIVIDUELLES
--#STEP()
DROP TABLE IF EXISTS EVALUATIONS_INDIVIDUELLES;
CREATE TABLE `EVALUATIONS_INDIVIDUELLES` (
  `EVAL_IND_ID` int(11) NOT NULL auto_increment,
  `EVAL_IND_COMMENTAIRE` varchar(200) NOT NULL,
  `EVAL_IND_DATE` date NOT NULL,
  `ID_COMPETENCE` int(11) NOT NULL,
  `ID_EVAL_COL` int(11) NOT NULL,
  `ID_ELEVE` int(11) NOT NULL,
  `ID_NOTE` int(11) NOT NULL,
  PRIMARY KEY  (`EVAL_IND_ID`),
  KEY `ID_COMPETENCE` (`ID_COMPETENCE`),
  KEY `ID_EVAL_COL` (`ID_EVAL_COL`),
  KEY `ID_NOTE` (`ID_NOTE`),
  KEY `ID_ELEVE` (`ID_ELEVE`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- Structure de la table MATIERES
--#STEP()
DROP TABLE IF EXISTS MATIERES;
CREATE TABLE `MATIERES` (
  `MATIERE_ID` int(11) NOT NULL auto_increment,
  `MATIERE_NOM` varchar(100) NOT NULL,
  `ID_DOMAINE` int(11) NOT NULL,
  PRIMARY KEY  (`MATIERE_ID`),
  KEY `ID_DOMAINE` (`ID_DOMAINE`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- Structure de la table NIVEAUX
--#STEP()
DROP TABLE IF EXISTS NIVEAUX;
CREATE TABLE `NIVEAUX` (
  `NIVEAU_ID` int(11) NOT NULL auto_increment,
  `NIVEAU_NOM` varchar(50) NOT NULL,
  `ID_CYCLE` int(11) NOT NULL,
  PRIMARY KEY  (`NIVEAU_ID`),
  KEY `ID_CYCLE` (`ID_CYCLE`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- Structure de la table NIVEAU_CLASSE
--#STEP()
DROP TABLE IF EXISTS NIVEAU_CLASSE;
CREATE TABLE `NIVEAU_CLASSE` (
  `ID_NIVEAU` int(11) NOT NULL,
  `ID_CLASSE` int(11) NOT NULL,
  PRIMARY KEY  (`ID_NIVEAU`,`ID_CLASSE`),
  KEY `ID_CLASSE` (`ID_CLASSE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

-- Structure de la table NOTES
--#STEP()
DROP TABLE IF EXISTS NOTES;
CREATE TABLE `NOTES` (
  `NOTE_ID` int(11) NOT NULL auto_increment,
  `NOTE_NOM` varchar(50) NOT NULL,
  `NOTE_LABEL` varchar(3) NOT NULL,
  `NOTE_NOTE` int(11) NOT NULL,
  PRIMARY KEY  (`NOTE_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- Structure de la table PERIODES
--#STEP()
DROP TABLE IF EXISTS PERIODES;
CREATE TABLE `PERIODES` (
  `PERIODE_ID` int(11) NOT NULL auto_increment,
  `PERIODE_NOM` varchar(10) NOT NULL,
  `PERIODE_DATE_DEBUT` varchar(16) NOT NULL,
  `PERIODE_DATE_FIN` varchar(16) NOT NULL,
  PRIMARY KEY  (`PERIODE_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- Structure de la table PROFESSEURS
--#STEP()
DROP TABLE IF EXISTS PROFESSEURS;
CREATE TABLE `PROFESSEURS` (
  `PROFESSEUR_ID` int(11) NOT NULL auto_increment,
  `PROFESSEUR_NOM` varchar(30) NOT NULL,
  `PROFESSEUR_PWD` varchar(50) NOT NULL,  
  PRIMARY KEY  (`PROFESSEUR_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- Structure de la table PROFESSEUR_CLASSE
--#STEP()
DROP TABLE IF EXISTS PROFESSEUR_CLASSE;
CREATE TABLE `PROFESSEUR_CLASSE` (
  `ID_CLASSE` int(11) NOT NULL,
  `ID_PROFESSEUR` int(11) NOT NULL,
  PRIMARY KEY  (`ID_CLASSE`,`ID_PROFESSEUR`),
  KEY `ID_PROFESSEUR` (`ID_PROFESSEUR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

-- Structure de la table PARAMETRES
--#STEP()
DROP TABLE IF EXISTS PARAMETRES;
CREATE TABLE PARAMETRES
(
	VERSION			VARCHAR(15)	NOT NULL,
	DATE_VERSION	DATETIME	NOT NULL	COMMENT 'Stocke la date de modification d''un fichier critique de l''application pour déterminer si une mise à jour est nécessaire.'
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8;

-- =============================================================================
--#TITLE(Contraintes pour les tables)

-- Contraintes pour la table CLASSES
--#STEP()
ALTER TABLE `CLASSES`
  ADD CONSTRAINT `CLASSES_ibfk_1` FOREIGN KEY (`ID_ECOLE`) REFERENCES `ECOLES` (`ECOLE_ID`) ON DELETE CASCADE;

-- Contraintes pour la table COMPETENCES
--#STEP()
ALTER TABLE `COMPETENCES`
  ADD CONSTRAINT `COMPETENCES_ibfk_1` FOREIGN KEY (`ID_MATIERE`) REFERENCES `MATIERES` (`MATIERE_ID`) ON DELETE CASCADE;

-- Contraintes pour la table DOMAINES
--#STEP()
ALTER TABLE `DOMAINES`
  ADD CONSTRAINT `DOMAINES_ibfk_1` FOREIGN KEY (`ID_CYCLE`) REFERENCES `CYCLES` (`CYCLE_ID`) ON DELETE CASCADE;

-- Contraintes pour la table ELEVE_CLASSE
--#STEP()
ALTER TABLE `ELEVE_CLASSE`
  ADD CONSTRAINT `ELEVE_CLASSE_ibfk_1` FOREIGN KEY (`ID_CLASSE`) REFERENCES `CLASSES` (`CLASSE_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `ELEVE_CLASSE_ibfk_2` FOREIGN KEY (`ID_ELEVE`) REFERENCES `ELEVES` (`ELEVE_ID`) ON DELETE CASCADE;

-- Contraintes pour la table EVALUATIONS_COLLECTIVES
--#STEP()
ALTER TABLE `EVALUATIONS_COLLECTIVES`
  ADD CONSTRAINT `EVALUATIONS_COLLECTIVES_ibfk_1` FOREIGN KEY (`ID_PERIODE`) REFERENCES `PERIODES` (`PERIODE_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `EVALUATIONS_COLLECTIVES_ibfk_2` FOREIGN KEY (`ID_CLASSE`) REFERENCES `CLASSES` (`CLASSE_ID`) ON DELETE CASCADE;

-- Contraintes pour la table EVALUATIONS_INDIVIDUELLES
--#STEP()
ALTER TABLE `EVALUATIONS_INDIVIDUELLES`
  ADD CONSTRAINT `EVALUATIONS_INDIVIDUELLES_ibfk_1` FOREIGN KEY (`ID_COMPETENCE`) REFERENCES `COMPETENCES` (`COMPETENCE_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `EVALUATIONS_INDIVIDUELLES_ibfk_2` FOREIGN KEY (`ID_EVAL_COL`) REFERENCES `EVALUATIONS_COLLECTIVES` (`EVAL_COL_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `EVALUATIONS_INDIVIDUELLES_ibfk_3` FOREIGN KEY (`ID_NOTE`) REFERENCES `NOTES` (`NOTE_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `EVALUATIONS_INDIVIDUELLES_ibfk_4` FOREIGN KEY (`ID_ELEVE`) REFERENCES `ELEVES` (`ELEVE_ID`) ON DELETE CASCADE;

-- Contraintes pour la table MATIERES
--#STEP()
ALTER TABLE `MATIERES`
  ADD CONSTRAINT `MATIERES_ibfk_1` FOREIGN KEY (`ID_DOMAINE`) REFERENCES `DOMAINES` (`DOMAINE_ID`) ON DELETE CASCADE;

-- Contraintes pour la table NIVEAUX
--#STEP()
ALTER TABLE `NIVEAUX`
  ADD CONSTRAINT `NIVEAUX_ibfk_1` FOREIGN KEY (`ID_CYCLE`) REFERENCES `CYCLES` (`CYCLE_ID`) ON DELETE CASCADE;

-- Contraintes pour la table NIVEAU_CLASSE
--#STEP()
ALTER TABLE `NIVEAU_CLASSE`
  ADD CONSTRAINT `NIVEAU_CLASSE_ibfk_1` FOREIGN KEY (`ID_CLASSE`) REFERENCES `CLASSES` (`CLASSE_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `NIVEAU_CLASSE_ibfk_2` FOREIGN KEY (`ID_NIVEAU`) REFERENCES `NIVEAUX` (`NIVEAU_ID`) ON DELETE CASCADE;

-- Contraintes pour la table PROFESSEUR_CLASSE
--#STEP()
ALTER TABLE `PROFESSEUR_CLASSE`
  ADD CONSTRAINT `PROFESSEUR_CLASSE_ibfk_1` FOREIGN KEY (`ID_CLASSE`) REFERENCES `CLASSES` (`CLASSE_ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `PROFESSEUR_CLASSE_ibfk_2` FOREIGN KEY (`ID_PROFESSEUR`) REFERENCES `PROFESSEURS` (`PROFESSEUR_ID`) ON DELETE CASCADE;

-- =============================================================================
--#TITLE(Contenu des tables systèmes)

--#STEP(TRANSACTION)

-- La seul ligne de la table paramètre
INSERT INTO PARAMETRES
	(VERSION, DATE_VERSION)
VALUES
	('0.0.0', '0000-00-00 00:00:00');

-- =============================================================================
--#TITLE(Contenu "spécial" de l'application)

--#STEP(TRANSACTION)
INSERT INTO `PROFESSEURS` (`PROFESSEUR_ID`, `PROFESSEUR_NOM`, `PROFESSEUR_PWD`) VALUES
(1, 'test', MD5('test'));

--#STEP(TRANSACTION)
-- Contenu de la table `NIVEAUX`
INSERT INTO `CYCLES` (`CYCLE_ID`, `CYCLE_NOM`) VALUES
(1, 'I'),
(2, 'II'),
(3, 'III');

-- Contenu de la table `NIVEAUX`
--#STEP(TRANSACTION)
INSERT INTO `NIVEAUX` (`NIVEAU_ID`, `NIVEAU_NOM`, `ID_CYCLE`) VALUES
(1, 'PS', 1),
(2, 'MS', 1),
(3, 'GS', 2),
(4, 'CP', 2),
(5, 'CE1', 2),
(6, 'CE2', 3),
(7, 'CM1', 3),
(8, 'CM2', 3);

-- Contenu de la table `NOTES`
--#STEP(TRANSACTION)
INSERT INTO `NOTES` (`NOTE_ID`, `NOTE_NOM`, `NOTE_LABEL`, `NOTE_NOTE`) VALUES
(1, 'Acquis', 'A', 20),
(2, 'A Renforcer', 'AR', 15),
(3, 'En cours d''acquisition', 'ECA', 10),
(4, 'Non Acquis', 'NA', 5),
(5, 'Non Evaluée', 'NE', 0);

-- Contenu de la table `PERIODES`
--#STEP(TRANSACTION)
INSERT INTO `PERIODES` (`PERIODE_ID`, `PERIODE_NOM`, `PERIODE_DATE_DEBUT`, `PERIODE_DATE_FIN`) VALUES
(1, 'p1', 'rentrée', 'toussaint'),
(2, 'p2', 'toussaint', 'noël'),
(3, 'p3', 'noël', 'février'),
(4, 'p4', 'février', 'pâques'),
(5, 'p5', 'pâques', 'été');

-- =============================================================================
--#TITLE(Activation des contraintes)

--#STEP(ALWAYS_RUN)
SET FOREIGN_KEY_CHECKS = 1;
