-- =============================================================================
-- Base de donnÃ©es          : baseeval
-- Version de l'application : 1.0.0.0
-- Mode                     : DROP and CREATE
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Base de donnÃ©es baseeval
--

DROP DATABASE IF EXISTS baseeval;
CREATE DATABASE baseeval;

-- CHARACTER SET utf8
-- COLLATE utf8_bin;

-- CHARACTER SET -> spÃ©cifie l'encodage
-- COLLATE -> spÃ©cifie la collation ("l'attitude" de mysql envers les donnÃ©es)
-- utf8 -> orthographe propre à mysql (absence du "-" entre utf et 8)
-- utf8_bin -> cette collation rend la comparaison de chaÃ®ne sensible à la casse (au contraire de utf8_general_

-- Si MySQL n'est pas configurÃ© par dÃ©faut pour l'UTF-8 il faut lui prÃ©ciser la maniÃ¨re dont elle doit traiter les caractÃ¨res contenus dans une requÃªte SQL à l'aide de cette instruction :
-- SET NAMES 'utf8';

USE baseeval;

-- -----------------------------------------------------------------------------
-- Structure de la table ECOLES
--

DROP TABLE IF EXISTS ECOLES;
CREATE TABLE ECOLES
(
	ECOLE_ID	INT					NOT NULL	AUTO_INCREMENT,
	ECOLE_NOM	VARCHAR(50)			NOT NULL,
	ECOLE_VILLE VARCHAR(50)			NOT NULL,
	ECOLE_DEPARTEMENT VARCHAR(5)	NOT NULL,

	CONSTRAINT PRIMARY KEY (ECOLE_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1;

-- -----------------------------------------------------------------------------
-- Structure de la table CLASSES
--

DROP TABLE IF EXISTS CLASSES;
CREATE TABLE CLASSES
(
	CLASSE_ID				INT 		NOT NULL	AUTO_INCREMENT,
	CLASSE_NOM				VARCHAR(10)	NOT NULL,
	CLASSE_ANNEE_SCOLAIRE	VARCHAR(9)	NOT NULL,
	ID_ECOLE				INT 		NOT NULL,

	CONSTRAINT PRIMARY KEY (CLASSE_ID),
	CONSTRAINT FOREIGN KEY (ID_ECOLE) REFERENCES ECOLES (ECOLE_ID) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1;

-- -----------------------------------------------------------------------------
-- Structure de la table PROFESSEURS
--

DROP TABLE IF EXISTS PROFESSEURS;
CREATE TABLE PROFESSEURS
(
	PROFESSEUR_ID	INT 		NOT NULL	AUTO_INCREMENT,
	PROFESSEUR_NOM	VARCHAR(30)	NOT NULL,

	CONSTRAINT PRIMARY KEY (PROFESSEUR_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1;

-- -----------------------------------------------------------------------------
-- Structure de la table PROFESSEUR_CLASSE
--

DROP TABLE IF EXISTS PROFESSEUR_CLASSE;
CREATE TABLE PROFESSEUR_CLASSE
(
	ID_CLASSE		INT NOT NULL,
	ID_PROFESSEUR	INT NOT NULL,

	CONSTRAINT PRIMARY KEY (ID_CLASSE, ID_PROFESSEUR),
	CONSTRAINT FOREIGN KEY (ID_CLASSE) REFERENCES CLASSES (CLASSE_ID) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (ID_PROFESSEUR) REFERENCES PROFESSEURS (PROFESSEUR_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- -----------------------------------------------------------------------------
-- Structure de la table ELEVES
--

DROP TABLE IF EXISTS ELEVES;
CREATE TABLE ELEVES
(
	ELEVE_ID				INT 		NOT NULL	AUTO_INCREMENT,
	ELEVE_NOM				VARCHAR(50)	NOT NULL,
	ELEVE_ACTIF				BOOLEAN		DEFAULT 1,
	ELEVE_DATE_NAISSANCE	DATE		NULL,

	CONSTRAINT PRIMARY KEY (ELEVE_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1;

-- -----------------------------------------------------------------------------
-- Structure de la table ELEVES
--

DROP TABLE IF EXISTS ELEVE_CLASSE;
CREATE TABLE ELEVE_CLASSE
(
	ID_ELEVE	INT	NOT NULL,
	ID_CLASSE	INT	NOT NULL,

	CONSTRAINT PRIMARY KEY (ID_ELEVE, ID_CLASSE),
	CONSTRAINT FOREIGN KEY (ID_CLASSE) REFERENCES CLASSES (CLASSE_ID) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (ID_ELEVE) REFERENCES ELEVES (ELEVE_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- -----------------------------------------------------------------------------
-- Structure de la table PERIODES
--

DROP TABLE IF EXISTS PERIODES;
CREATE TABLE PERIODES
(
	PERIODE_ID			INT 		NOT NULL	AUTO_INCREMENT,
	PERIODE_NOM			VARCHAR(10)	NOT NULL,
	PERIODE_DATE_DEBUT	VARCHAR(16)	NOT NULL,
	PERIODE_DATE_FIN	VARCHAR(16)	NOT NULL,

	CONSTRAINT PRIMARY KEY (PERIODE_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1;

-- -----------------------------------------------------------------------------
-- Structure de la table EVALUATIONS_COLLECTIVES
--

DROP TABLE IF EXISTS EVALUATIONS_COLLECTIVES;
CREATE TABLE EVALUATIONS_COLLECTIVES
(
	EVAL_COL_ID				INT 			NOT NULL	AUTO_INCREMENT,
	EVAL_COL_NOM			VARCHAR(50)		NOT NULL,
	EVAL_COL_DESCRIPTION	VARCHAR(200)	NOT NULL,
	EVAL_COL_DATE			DATE			NOT NULL,
	ID_PERIODE				INT				NOT NULL,
	ID_CLASSE				INT				NOT NULL,

	CONSTRAINT PRIMARY KEY (EVAL_COL_ID),
	CONSTRAINT FOREIGN KEY (ID_PERIODE) REFERENCES PERIODES (PERIODE_ID) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (ID_CLASSE) REFERENCES CLASSES (CLASSE_ID) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1;

-- -----------------------------------------------------------------------------
-- Structure de la table CYCLES
--

DROP TABLE IF EXISTS CYCLES;
CREATE TABLE CYCLES
(
	CYCLE_ID	INT 		NOT NULL	AUTO_INCREMENT,
	CYCLE_NOM	VARCHAR(50)	NOT NULL,

	CONSTRAINT PRIMARY KEY (CYCLE_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1;

-- -----------------------------------------------------------------------------
-- Structure de la table NIVEAUX
--

DROP TABLE IF EXISTS NIVEAUX;
CREATE TABLE NIVEAUX
(
	NIVEAU_ID	INT 		NOT NULL	AUTO_INCREMENT,
	NIVEAU_NOM	VARCHAR(50)	NOT NULL,
	ID_CYCLE	INT 		NOT NULL,

	CONSTRAINT PRIMARY KEY (NIVEAU_ID),
	CONSTRAINT FOREIGN KEY (ID_CYCLE) REFERENCES CYCLES (CYCLE_ID) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1;

-- -----------------------------------------------------------------------------
-- Structure de la table NIVEAU_CLASSE
--

DROP TABLE IF EXISTS NIVEAU_CLASSE;
CREATE TABLE NIVEAU_CLASSE
(
	ID_NIVEAU	INT NOT NULL,
	ID_CLASSE	INT NOT NULL,

	CONSTRAINT PRIMARY KEY (ID_NIVEAU, ID_CLASSE),
	CONSTRAINT FOREIGN KEY (ID_CLASSE) REFERENCES CLASSES (CLASSE_ID) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (ID_NIVEAU) REFERENCES NIVEAUX (NIVEAU_ID) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1;

-- -----------------------------------------------------------------------------
-- Structure de la table DOMAINES
--

DROP TABLE IF EXISTS DOMAINES;
CREATE TABLE DOMAINES
(
	DOMAINE_ID	INT 			NOT NULL	AUTO_INCREMENT,
	DOMAINE_NOM	VARCHAR(100)	NOT NULL,
	ID_CYCLE	INT 			NOT NULL,

	CONSTRAINT PRIMARY KEY (DOMAINE_ID),
	CONSTRAINT FOREIGN KEY (ID_CYCLE) REFERENCES CYCLES (CYCLE_ID) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1;

-- -----------------------------------------------------------------------------
-- Structure de la table MATIERES
--

DROP TABLE IF EXISTS MATIERES;
CREATE TABLE MATIERES
(
	MATIERE_ID	INT 			NOT NULL	AUTO_INCREMENT,
	MATIERE_NOM	VARCHAR(100)	NOT NULL,
	ID_DOMAINE	INT 			NOT NULL,

	CONSTRAINT PRIMARY KEY (MATIERE_ID),
	CONSTRAINT FOREIGN KEY (ID_DOMAINE) REFERENCES DOMAINES (DOMAINE_ID) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1;

-- -----------------------------------------------------------------------------
-- Structure de la table COMPETENCES
-- 

DROP TABLE IF EXISTS COMPETENCES;
CREATE TABLE COMPETENCES
(
	COMPETENCE_ID	INT 			NOT NULL	AUTO_INCREMENT,
	COMPETENCE_NOM	VARCHAR(200)	NOT NULL,
	ID_MATIERE		INT 			NOT NULL,

	CONSTRAINT PRIMARY KEY (COMPETENCE_ID),
	CONSTRAINT FOREIGN KEY (ID_MATIERE) REFERENCES MATIERES (MATIERE_ID) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1;

-- -----------------------------------------------------------------------------
-- Structure de la table NOTES
--

DROP TABLE IF EXISTS NOTES;
CREATE TABLE NOTES
(
	NOTE_ID		INT 		NOT NULL	AUTO_INCREMENT,
	NOTE_NOM	VARCHAR(50)	NOT NULL,
	NOTE_LABEL	VARCHAR(3)	NOT NULL,
	NOTE_NOTE	INT			NOT NULL,

	CONSTRAINT PRIMARY KEY (NOTE_ID)
) ENGINE=InnoDB AUTO_INCREMENT=1;

-- -----------------------------------------------------------------------------
-- Structure de la table EVALUATIONS_INDIVIDUELLES
--

DROP TABLE IF EXISTS EVALUATIONS_INDIVIDUELLES;
CREATE TABLE EVALUATIONS_INDIVIDUELLES
(
	EVAL_IND_ID				INT 			NOT NULL	AUTO_INCREMENT,
	EVAL_IND_COMMENTAIRE	VARCHAR(200)	NOT NULL,
	EVAL_IND_DATE			DATE			NOT NULL,
	ID_COMPETENCE			INT				NOT NULL,
	ID_EVAL_COL				INT				NOT NULL,
	ID_ELEVE				INT				NOT NULL,
	ID_NOTE					INT				NOT NULL,

	CONSTRAINT PRIMARY KEY (EVAL_IND_ID),
	CONSTRAINT FOREIGN KEY (ID_COMPETENCE) REFERENCES COMPETENCES (COMPETENCE_ID) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (ID_EVAL_COL) REFERENCES EVALUATIONS_COLLECTIVES (EVAL_COL_ID) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (ID_NOTE) REFERENCES NOTES (NOTE_ID) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (ID_ELEVE) REFERENCES ELEVES (ELEVE_ID) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1;

