-- CE SCRIPT EST UNIQUEMENT PRESENT POUR CREER UNE PREMIERE BASE AVEC DES VALEURS DE TEST
-- A JOUER APRES INSTALL.SQL

-- CONTENU INVARIABLE

-- CYCLES
INSERT INTO CYCLES(CYCLE_NOM) VALUE('I');
INSERT INTO CYCLES(CYCLE_NOM) VALUE('II');
INSERT INTO CYCLES(CYCLE_NOM) VALUE('III');

-- NIVEAUX
INSERT INTO NIVEAUX(NIVEAU_NOM, ID_CYCLE) VALUE('ps',1);
INSERT INTO NIVEAUX(NIVEAU_NOM, ID_CYCLE) VALUE('ms',1);
INSERT INTO NIVEAUX(NIVEAU_NOM, ID_CYCLE) VALUE('gs',2);
INSERT INTO NIVEAUX(NIVEAU_NOM, ID_CYCLE) VALUE('cp',2);
INSERT INTO NIVEAUX(NIVEAU_NOM, ID_CYCLE) VALUE('ce1',2);
INSERT INTO NIVEAUX(NIVEAU_NOM, ID_CYCLE) VALUE('ce2',3);
INSERT INTO NIVEAUX(NIVEAU_NOM, ID_CYCLE) VALUE('cm1',3);
INSERT INTO NIVEAUX(NIVEAU_NOM, ID_CYCLE) VALUE('cm2',3);

-- PERIODES
INSERT INTO PERIODES(PERIODE_NOM, PERIODE_DATE_DEBUT, PERIODE_DATE_FIN) VALUE('p1', 'septembre', 'toussaint');
INSERT INTO PERIODES(PERIODE_NOM, PERIODE_DATE_DEBUT, PERIODE_DATE_FIN) VALUE('p2', 'toussaint', 'noÃ«l');
INSERT INTO PERIODES(PERIODE_NOM, PERIODE_DATE_DEBUT, PERIODE_DATE_FIN) VALUE('p3', 'noÃ«l', "vacances d'hiver");
INSERT INTO PERIODES(PERIODE_NOM, PERIODE_DATE_DEBUT, PERIODE_DATE_FIN) VALUE('p4', "vacances d'hiver", 'pÃ¢ques');
INSERT INTO PERIODES(PERIODE_NOM, PERIODE_DATE_DEBUT, PERIODE_DATE_FIN) VALUE('p5', 'pÃ¢ques', 'été');

-- DOMAINES
INSERT INTO DOMAINES(ID_CYCLE, DOMAINE_NOM) SELECT CYCLE_ID, "Le langage au coeur des apprentissages" FROM CYCLES WHERE CYCLE_NOM="I";
INSERT INTO DOMAINES(ID_CYCLE, DOMAINE_NOM) SELECT CYCLE_ID, "Vivre ensemble" FROM CYCLES WHERE CYCLE_NOM="I";
INSERT INTO DOMAINES(ID_CYCLE, DOMAINE_NOM) SELECT CYCLE_ID, "Agir et s'exprimer avec son corps" FROM CYCLES WHERE CYCLE_NOM="I";
INSERT INTO DOMAINES(ID_CYCLE, DOMAINE_NOM) SELECT CYCLE_ID, "Découverte du monde" FROM CYCLES WHERE CYCLE_NOM="I";
INSERT INTO DOMAINES(ID_CYCLE, DOMAINE_NOM) SELECT CYCLE_ID, "La sensibilité, l'imagination, la création" FROM CYCLES WHERE CYCLE_NOM="I";
INSERT INTO DOMAINES(ID_CYCLE, DOMAINE_NOM) SELECT CYCLE_ID, "MaÃ®trise du langage et de la langue franÃ§aise" FROM CYCLES WHERE CYCLE_NOM="II";
INSERT INTO DOMAINES(ID_CYCLE, DOMAINE_NOM) SELECT CYCLE_ID, "Mathématiques" FROM CYCLES WHERE CYCLE_NOM="II";
INSERT INTO DOMAINES(ID_CYCLE, DOMAINE_NOM) SELECT CYCLE_ID, "Vivre ensemble" FROM CYCLES WHERE CYCLE_NOM="II";
INSERT INTO DOMAINES(ID_CYCLE, DOMAINE_NOM) SELECT CYCLE_ID, "Découvrir le monde" FROM CYCLES WHERE CYCLE_NOM="II";
INSERT INTO DOMAINES(ID_CYCLE, DOMAINE_NOM) SELECT CYCLE_ID, "Langues étrangÃ¨res ou régionales" FROM CYCLES WHERE CYCLE_NOM="II";
INSERT INTO DOMAINES(ID_CYCLE, DOMAINE_NOM) SELECT CYCLE_ID, "Education artistique" FROM CYCLES WHERE CYCLE_NOM="II";
INSERT INTO DOMAINES(ID_CYCLE, DOMAINE_NOM) SELECT CYCLE_ID, "Education physique et sportive" FROM CYCLES WHERE CYCLE_NOM="II";
INSERT INTO DOMAINES(ID_CYCLE, DOMAINE_NOM) SELECT CYCLE_ID, "Langue franÃ§aise, éducation littéraire et humaine" FROM CYCLES WHERE CYCLE_NOM="III";
INSERT INTO DOMAINES(ID_CYCLE, DOMAINE_NOM) SELECT CYCLE_ID, "Education scientifique" FROM CYCLES WHERE CYCLE_NOM="III";
INSERT INTO DOMAINES(ID_CYCLE, DOMAINE_NOM) SELECT CYCLE_ID, "Education artistique" FROM CYCLES WHERE CYCLE_NOM="III";
INSERT INTO DOMAINES(ID_CYCLE, DOMAINE_NOM) SELECT CYCLE_ID, "Education physique et sportive" FROM CYCLES WHERE CYCLE_NOM="III";

-- MATIERES
-- CYCLE 1
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(1,"Communication");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(1,"Langage d'accompagnement de l'action");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(1,"Langage d'évocation");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(1,"Langage écrit");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(3,"Réaliser une action que l'on peut mesurer");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(3,"Adapter ses déplacements à différents types d'environnements");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(3,"Coopérer et s'opposer individuellement et collectivement");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(3,"Réaliser des activités à visée artistique, esthétique ou expressive");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(4,"Découverte sensorielle");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(4,"Exploration du monde de la matiÃ¨re et  des objets");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(4,"Découvrir le monde du vivant, de l'environnement, de l'hygiÃ¨ne et de la santé.");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(4,"Repérages dans l'espace");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(4,"Le temps qui passe");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(4,"Découverte des formes et des grandeurs");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(4,"Approche des quantités et des nombres");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(5,"Le regard et le geste");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(5,"La voix et l'écoute");
-- CYCLE 2
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(6,"MaÃ®trise du langage oral");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(6,"Lecture et écriture");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(7,"Exploitation de données numériques");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(7,"Connaissance des nombres entiers naturels");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(7,"Calcul");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(7,"Espace et géométrie");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(7,"Grandeurs et mesures");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(9,"Domaine de l'espace");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(9,"Domaine du temps");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(9,"Domaine du vivant");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(9,"Domaine de la matiÃ¨re, des objets et des techniques de l'information et de la communication");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(11,"Arts visuels");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(11,"Education musicale");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(12,"Réaliser une performance mesurée");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(12,"Adapter ses déplacements à différents types d'environnements");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(12,"S'opposer individuellement ou collectivement");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(12,"Concevoir et réaliser des actions à visée artistique, esthétique ou expressive");
-- CYCLE 3
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(13,"Littérature");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(13,"ORLF");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(13,"Langue étrangÃ¨re ou régionale");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(13,"Histoire et géographie");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(13,"Débat réglé");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(14,"Mathématiques");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(14,"Sciences expérimentales et technologie");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(15,"Arts visuels");
INSERT INTO MATIERES(ID_DOMAINE, MATIERE_NOM) VALUE(15,"Education musicale");

-- COMPETENCES
INSERT INTO COMPETENCES(ID_MATIERE, COMPETENCE_NOM) VALUE(43,"Etre capable d'interpréter de mémoire plus de 10 chansons parmi celles qui ont été apprises");
INSERT INTO COMPETENCES(ID_MATIERE, COMPETENCE_NOM) VALUE(43,"ContrÃ´ler volontairement sa voix et son attitude corporelle pour chanter");
INSERT INTO COMPETENCES(ID_MATIERE, COMPETENCE_NOM) VALUE(43,"Tenir sa voix et sa place en formation chorale");
INSERT INTO COMPETENCES(ID_MATIERE, COMPETENCE_NOM) VALUE(43,"Assumer son rÃ´le dans un travail d'accompagnement");
INSERT INTO COMPETENCES(ID_MATIERE, COMPETENCE_NOM) VALUE(1,"Etre capable de répondre aux sollicitations de l'adulte en se faisant comprendre dÃ¨s la fin de la premiÃ¨re année de la scolarité");
INSERT INTO COMPETENCES(ID_MATIERE, COMPETENCE_NOM) VALUE(1,"Prendre l'initiative d'un échange et le tenir au-delà de la premiÃ¨re réponse");
INSERT INTO COMPETENCES(ID_MATIERE, COMPETENCE_NOM) VALUE(1,"Participer à un échange collectif en acceptant d'écouter autrui en attendant son tour de parole et en restant dans le propos de l'échange");

-- NOTES
INSERT INTO NOTES(NOTE_NOM, NOTE_LABEL, NOTE_NOTE) VALUE("Acquis", "A", 20);
INSERT INTO NOTES(NOTE_NOM, NOTE_LABEL, NOTE_NOTE) VALUE("A renforcer", "AR", 15);
INSERT INTO NOTES(NOTE_NOM, NOTE_LABEL, NOTE_NOTE) VALUE("En cours d'acquisition", "ECA", 10);
INSERT INTO NOTES(NOTE_NOM, NOTE_LABEL, NOTE_NOTE) VALUE("Non Acquis", "NA", 5);

-- CONTENU VARIABLE MAIS POUR TESTS

-- PROFESSEURS
INSERT INTO PROFESSEURS(PROFESSEUR_NOM) VALUE('Christelle Héritier');
INSERT INTO PROFESSEURS(PROFESSEUR_NOM) VALUE('Arnaud Péchon');
INSERT INTO PROFESSEURS(PROFESSEUR_NOM) VALUE('Solange Rolland');
INSERT INTO PROFESSEURS(PROFESSEUR_NOM) VALUE('Julie Riccioz');
INSERT INTO PROFESSEURS(PROFESSEUR_NOM) VALUE('Elodie Romanelli');
INSERT INTO PROFESSEURS(PROFESSEUR_NOM) VALUE('Adrien Lange');
INSERT INTO PROFESSEURS(PROFESSEUR_NOM) VALUE('Anthony Pasquet');

-- ECOLES
INSERT INTO ECOLES(ECOLE_NOM, ECOLE_VILLE, ECOLE_DEPARTEMENT) VALUE('Edouard Vaillant', 'Le Blanc Mesnil', '93150');
INSERT INTO ECOLES(ECOLE_NOM, ECOLE_VILLE, ECOLE_DEPARTEMENT) VALUE('Jules VallÃ¨s', 'Saint-Denis', '93200');

-- CLASSES
INSERT INTO CLASSES(CLASSE_NOM, CLASSE_ANNEE_SCOLAIRE, ID_ECOLE) VALUE('ce2c','2006-2007',2);
INSERT INTO CLASSES(CLASSE_NOM, CLASSE_ANNEE_SCOLAIRE, ID_ECOLE) VALUE('ce1b','2007-2008',1);
INSERT INTO CLASSES(CLASSE_NOM, CLASSE_ANNEE_SCOLAIRE, ID_ECOLE) VALUE('ce2a','2007-2008',1);

-- NIVEAU_CLASSE
INSERT INTO NIVEAU_CLASSE(ID_CLASSE, ID_NIVEAU) VALUE(1,6);
INSERT INTO NIVEAU_CLASSE(ID_CLASSE, ID_NIVEAU) VALUE(2,5);
INSERT INTO NIVEAU_CLASSE(ID_CLASSE, ID_NIVEAU) VALUE(3,6);

-- LIENS
INSERT INTO PROFESSEUR_CLASSE(ID_PROFESSEUR, ID_CLASSE) VALUE(1,1);
INSERT INTO PROFESSEUR_CLASSE(ID_PROFESSEUR, ID_CLASSE) VALUE(1,2);
INSERT INTO PROFESSEUR_CLASSE(ID_PROFESSEUR, ID_CLASSE) VALUE(1,3);

-- ELEVES - annee scolaire 2006-2007 - professeur Christelle Héritier
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('ATIA Lara', STR_TO_DATE('26/03/1998', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('BERNARDO Kévin', STR_TO_DATE('12/10/1998', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('BONJEAN-TRAÃA Nahida', STR_TO_DATE('01/08/1998', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('BORKOWSKI Souad', STR_TO_DATE('10/01/1998', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('BOUNAROUF Nisrine', STR_TO_DATE('10/12/1998', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('BROU Marie-Claude', STR_TO_DATE('07/08/1998', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('CISSE Boubou', STR_TO_DATE('04/05/1998', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('DIOURI Manal', STR_TO_DATE('29/04/1998', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('DJORDJEVIC Sanéla', STR_TO_DATE('02/07/1998', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('FARKAS Iosif', STR_TO_DATE('24/02/1997', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('FERHAT Kathia', STR_TO_DATE('10/01/1998', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('FORTUNE Axelle', STR_TO_DATE('17/02/1998', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('HADJ SAÃD Nassim', STR_TO_DATE('03/12/1997', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('KARAMOKO Sindou', STR_TO_DATE('06/04/1998', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('KIMAKUIZA Brandon', STR_TO_DATE('05/09/1998', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('LAGRAVE Délizia', STR_TO_DATE('21/02/1997', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('OURTIRANE Sara', STR_TO_DATE('22/10/1998', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('PERRONE Shana', STR_TO_DATE('27/09/1998', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('SIMAO-MANUEL Calvin', STR_TO_DATE('07/12/1997', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('SOUAM Lahlou', STR_TO_DATE('02/06/1998', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('TOUBI Soumia', STR_TO_DATE('08/10/1998', '%d/%m/%Y'));

-- ELEVE_CLASSE - annee scolaire 2006-2007 - professeur Christelle Heritier
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(1,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(2,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(3,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(4,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(5,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(6,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(7,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(8,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(9,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(10,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(11,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(12,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(13,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(14,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(15,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(16,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(17,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(18,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(19,1);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(20,1);

-- ELEVES - annee scolaire 2007-2008 - professeur Christelle Héritier
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('ANDRE Rachel', STR_TO_DATE('19/11/1999', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('BALABAN Emré', STR_TO_DATE('30/05/2000', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('BARTHOLET Prince', STR_TO_DATE('09/08/2000', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('BOUABID Charaf', STR_TO_DATE('08/07/2000', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('DIAS Margaux', STR_TO_DATE('19/11/1999', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('HABASHY Marcelino', STR_TO_DATE('14/03/2000', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('HAMILA Ahmed', STR_TO_DATE('18/02/2000', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('IDRI Amanda', STR_TO_DATE('27/10/2000', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('KARUNAKARAN Nivetha', STR_TO_DATE('19/06/2000', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('KENNY Clovis', STR_TO_DATE('06/09/2000', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('KUBEZYK Kelly', STR_TO_DATE('13/03/2000', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('LAL Joyti', STR_TO_DATE('04/05/2000', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('MAHIOUT Laurine', STR_TO_DATE('08/07/1999', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('MALIK Iraj', STR_TO_DATE('19/02/2000', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('MUNAWAR Junaid', STR_TO_DATE('10/02/1999', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('NACER Yacine', STR_TO_DATE('04/07/2000', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('RAHMOUN Ousama', STR_TO_DATE('08/04/2000', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('SIMOES Sylvain', STR_TO_DATE('31/12/1999', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('SOVILJ Stefan', STR_TO_DATE('28/05/2000', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('TWAYA Enoch', STR_TO_DATE('16/06/2000', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('WAGGEH Fatoumata', STR_TO_DATE('16/03/1998', '%d/%m/%Y'));
INSERT INTO ELEVES(ELEVE_NOM, ELEVE_DATE_NAISSANCE) VALUE('WIJAYAKUMAR Diepthyia', STR_TO_DATE('16/06/2000', '%d/%m/%Y'));

-- ELEVE_CLASSE - annee scolaire 2007-2008 - professeur Christelle Heritier
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(21,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(22,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(23,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(24,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(25,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(26,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(27,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(28,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(29,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(30,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(31,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(32,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(33,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(34,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(35,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(36,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(37,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(38,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(39,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(40,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(41,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(42,2);
INSERT INTO ELEVE_CLASSE(ID_ELEVE, ID_CLASSE) VALUE(43,2);

